version: "3.8"
services:
  front-end:
    build: ./front-end
    container_name: frontend_c
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  back-end:
    build: ./back-end
    container_name: backend_c
    ports:
      - "3021:3021"
    stdin_open: true
    tty: true
